core
main2

diff --git a/PkgFiles/gcc-pkg b/PkgFiles/gcc-pkg
--- a/PkgFiles/gcc-pkg
+++ b/PkgFiles/gcc-pkg
@@ -102,4 +102,13 @@ else
     echo "failed"
     exit 1
 fi
+cd ..
+cat gcc/limitx.h gcc/glimits.h gcc/limity.h > \
+ `dirname $($LFS_TGT-gcc -print-libgcc-file-name)`/include/limits.h
+  if [ $? -eq 0 ]; then
+    echo "succeeded"
+else
+    echo "failed"
+    exit 1
+fi
 touch $LFS/pkg_pass/gcc-pass1
